site_name: 飛行書卷 - 精要索引
site_url: https://canaan-land.github.io/s-books
copyright: Copyright &copy; 2024 Canaan Land
extra:
  social:
    - icon: material/github
      link: https://github.com/canaan-land/s-books
    - icon: material/web
      link: https://sites.google.com/view/canaanland-organic
extra_css:
  - 'stylesheets/extra.css'
theme:
  name: material
  language: zh-TW
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.share
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - glightbox
  - search:
      jieba_dict: "jieba/dict.txt"
  - print-site

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  
nav:
  - 首頁: index.md
  - 江端儀敬錄書籍:
    - 生命證道集: 江端儀敬錄書籍/生命證道集.md
    - 提防異端: 江端儀敬錄書籍/提防異端.md
    - 金燈台（一）: 江端儀敬錄書籍/金燈台（一）.md
    - 金燈台（二）: 江端儀敬錄書籍/金燈台（二）.md
    - 看哪！神榮耀的作為: 江端儀敬錄書籍/看哪！神榮耀的作為.md
    - 我們為了辯明真理: 江端儀敬錄書籍/我們為了辯明真理.md
    - 進神的國: 江端儀敬錄書籍/進神的國.md
    - 以斯帖記: 江端儀敬錄書籍/以斯帖記.md
    - 聖靈行傳（上）: 江端儀敬錄書籍/聖靈行傳（上）.md
    - 聖靈行傳（下）: 江端儀敬錄書籍/聖靈行傳（下）.md
    - 論女人蒙頭和先知講道: 江端儀敬錄書籍/論女人蒙頭和先知講道.md
    - 神使女江端儀姊妹蒙召事主年表: 江端儀敬錄書籍/神使女江端儀姊妹蒙召事主年表.md
  - 洪以利亞敬錄書籍:
    - 教會的建造: 洪以利亞敬錄書籍/教會的建造.md
    - 不違背那從天上來的異象: 洪以利亞敬錄書籍/不違背那從天上來的異象.md
    - 舌音見證: 洪以利亞敬錄書籍/舌音見證.md
    - 耶路撒冷的守望聖者: 洪以利亞敬錄書籍/耶路撒冷的守望聖者.md
    - 尼希米記: 洪以利亞敬錄書籍/尼希米記.md
    - 神所揀選的一個人一座山: 洪以利亞敬錄書籍/神所揀選的一個人一座山.md
    - 使徒職分: 洪以利亞敬錄書籍/使徒職分.md
    - 靈的操練與己生命的對付: 洪以利亞敬錄書籍/靈的操練與己生命的對付.md
    - 擘餅記念主: 洪以利亞敬錄書籍/擘餅記念主.md
    - 帶下救恩曙光的器皿: 洪以利亞敬錄書籍/帶下救恩曙光的器皿.md
    - 屬靈伊甸長屋: 洪以利亞敬錄書籍/屬靈伊甸長屋.md
  - GJCC書籍:
    - 以斯拉記: GJCC書籍/以斯拉記.md
    - 話家常: GJCC書籍/話家常.md
    - 好牧人: GJCC書籍/好牧人.md